version: '3'
services:
  cbsurge:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./create_user.sh:/app/create_user.sh
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./Makefile:/app/Makefile
      - ./cbsurge:/app/cbsurge # mount app folder to container
      - ./tests:/app/tests
    entrypoint: "/app/entrypoint.sh"
    ports:
      - 2222:22
    environment:
      - SSH_USERS=${SSH_USERS:-''}