services:
  rapida:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./Makefile:/app/Makefile
      - ./cbsurge:/app/cbsurge # mount app folder to container
      - ./tests:/app/tests
      # uncomment to mount token info from local
      # - ~/.cbsurge:/root/.cbsurge
      # uncomment to mount data folder from local
      # - ./data:/data
    ports:
      - 8100:8000
    env_file:
      - .env
