[project]
name = "geo-cb-surge"
version = "0.0.1"
description = "python tools that facilitate the assessment of natural hazards over various domains like population, landuse, infrastructure, etc"
requires-python = ">=3.12"
authors = [
    { name = 'Ioan Ferencik'},
    { name = 'Joseph Thuha'},
    { name = 'Jin Igarashi'},
    { name = "United Nations Development Programme", email = "data@undp.org" }
]
readme = "README.md"
dependencies = [
    "httpx",
    "osm2geojson",
    "shapely",
    "h3",
    "tqdm",
    "GDAL == 3.10.0",
    "azure-storage-blob",
    "overturemaps",
    "async",
    "aiofiles",
    "aiohttp",
    "azure-storage-file-share",
    "asyncclick",
    "rio-cogeo",
    "exactextract",
    "pycountry",
    "click",
    "pyarrow",
    "azure-core",
    "rasterio",
    "geopandas",
    "azure-identity",
    "rich",
    "morecantile",
    "mapbox_vector_tile",
    "aiopmtiles @ git+https://github.com/developmentseed/aiopmtiles",
    "sympy",
    "pydantic",
    "pmtiles",
    "msal",
    "playwright"
]

[project.optional-dependencies]
# dependencies required for development
dev = [
    "pytest"
]

# dependencies required for Jupyter server
jupyter = [
    "jupyterhub",
    "jupyterlab",
    "notebook",
    "dockerspawner",
    "matplotlib",
    "jupyterlab_widgets",
    "ipywidgets",
    "leafmap",
    "mapclassify",
    "xarray",
    "localtileserver"
]

[project.scripts]
rapida = "cbsurge.cli:cli"

[project.urls]
Homepage = "https://github.com/UNDP-Data/geo-cb-surge"
Documentation = "https://github.com/UNDP-Data/geo-cb-surge"
Repository = "https://github.com:UNDP-Data/geo-cb-surge.git"
Issues = "https://github.com/UNDP-Data/geo-cb-surge/issues"
#Changelog = "https://github.com/UNDP-Data/geo-cb-surge/blob/master/CHANGELOG.md"

[tool.hatch.build.targets.wheel]
    packages = ["cbsurge"]

[tool.hatch.build.targets.sdist]
exclude = [
    ".devcontainer",
    ".github",
    ".dockerignore",
    "docker-compose.yml",
    "Dockerfile",
    ".gitignore",
    ".pre-commit-config.yaml",
    "tests",
    "Makefile"
]

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

#[tool.hatchling.dependencies]
#GDAL = ">=3.6.0, <4.0.0"  # Specify the GDAL version range